In [7]:
import numpy as np

In [8]:
dizi = np.arange(0,24)

In [9]:
dizikopyasi = dizi.copy()

In [11]:
dizikopyasisilicing = dizikopyasi[3:6]

In [12]:
dizikopyasisilicing[:] = 500

In [17]:
dizi



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
dizikopyasi

array([  0,   1,   2, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [19]:
dizikopyasisilicing

array([500, 500, 500])

# matrix

In [20]:
ornekmatrix = np.arange(0,30)

In [21]:
ornekmatrix = ornekmatrix.reshape(5,6)

In [26]:
ornekmatrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
ornekmatrix[1][3]

9

In [30]:
ornekmatrix[:, 3]

array([ 3,  9, 15, 21, 27])

In [36]:
ornekmatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])