# arange

In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [21]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

# EYE

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# random

In [23]:
np.random.randn(8) 

array([ 1.46961072, -0.73344726, -0.83955275, -0.52196348, -1.69170616,
       -0.47195776, -0.2760222 ,  0.70739773])

In [24]:
np.random.randn(4,4)

array([[ 0.55105155,  0.2899981 , -0.87313333, -2.25486627],
       [-0.38739437,  1.45262891, -0.71338748,  0.1367712 ],
       [ 1.05305679,  0.35926075, -1.03758129, -0.50451151],
       [ 0.70547645,  0.75037527, -0.90072744, -0.36561071]])

In [34]:
np.random.randint(1,10)

7

In [35]:
np.random.randint(1,10,5)

array([4, 6, 4, 2, 5])

In [38]:
randomdizi = np.random.randint(0,100,20)
randomdizi

array([63, 89, 73, 49, 63, 98, 64, 83, 83, 90, 69, 15, 61, 88, 97, 40, 96,
       36, 70, 49])

In [39]:
npdizi = np.arange(0,30)
npdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# numpy dizi methodları

In [40]:
npdizi.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [41]:
np.max(npdizi)

29

In [42]:
npdizi.max()

29

In [44]:
randomdizi.argmax()

5