In [1]:
import numpy as np

In [2]:
dizi = np.random.randint(0,100,20)

In [3]:
dizi

array([ 5, 91, 82, 56, 22, 86, 60, 60, 40, 77, 91, 32, 82, 49, 49, 66, 55,
       52, 35, 75])

In [4]:
dizi > 24

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
sonuc = dizi >24

In [6]:
dizi[dizi>24]

array([91, 82, 56, 86, 60, 60, 40, 77, 91, 32, 82, 49, 49, 66, 55, 52, 35,
       75])

In [7]:
dizi[sonuc]

array([91, 82, 56, 86, 60, 60, 40, 77, 91, 32, 82, 49, 49, 66, 55, 52, 35,
       75])

In [8]:
sondizi = np.arange(0,24)

In [9]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
sondizi+sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [11]:
sondizi*sondizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [13]:
sondizi/sondizi

<ipython-input-13-c3c378435acd>:1: RuntimeWarning: invalid value encountered in true_divide
  sondizi/sondizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])